#!/usr/bin/env python3
"""DQAEIP portable release — release manifest + release lock
(task-book sections 32 and 33).

Release manifest (§32): cryptographic manifest over the release tree
(every file that will enter the ZIP), each entry carrying path,
SHA-256, size, role, artifact identity, source dependency, generator,
generator SHA, and the evidence fingerprint.

Release lock (§33): the locked release identity —
    release ID / FINAL_RESULTS SHA / evidence fingerprint /
    dependency fingerprint / Frozen V1 SHA / official input SHA /
    official output SHA / release manifest SHA / status LOCKED

Any subsequent modification to a locked artifact INVALIDATES the lock
(the integrity monitor's release-drift check enforces this).
"""

import hashlib
import json
import os
import subprocess
import sys
import time

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from data_quality_platform.assurance.integrity import (  # noqa: E402
    OFFICIAL_EVIDENCE_DIR, OFFICIAL_INPUT_SHA256, OFFICIAL_OUTPUT_SHA256,
    UPDATE_ID, FROZEN_V1_SOURCE, sha256_file)

NS = "evidence/FINAL_CLEAN_REBUILD_RELEASE_2026-09-18"
MANIFEST_OUT = os.path.join(REPO_ROOT, NS, "release_manifest",
                            "release_manifest.json")
LOCK_OUT = os.path.join(REPO_ROOT, NS, "release_manifest",
                        "release_lock.json")

RELEASE_ID = "DQAEIP-FINAL-CLEAN-REBUILD-RELEASE-2026-09-18"

# The ZIP itself and records about the ZIP cannot be inside the ZIP:
# self-referential artifacts are excluded from the manifest.
SELF_REFERENTIAL_PREFIXES = (
    f"{NS}/release_manifest/",
    # the freshness report is a post-manifest runtime evaluation
    # (built after the snapshot so its state is reproducible at the
    # terminal tree); pinning it here would be circular.
    f"{NS}/freshness/",
    # the self-contained verification record describes the archive
    # and is necessarily written after it.
    f"{NS}/self_contained_verification/",
    # the final forensic audit is a post-archive read-only runtime
    # record.
    f"{NS}/final_audit/",
    # post-manifest finalize outputs: the claim graph value-anchors
    # the integrity monitor report (generated after the snapshot,
    # which pins this manifest), so it is finalized after the
    # manifest; the registry and schema report build on it. They are
    # hash-pinned by the ZIP member manifest + per-member SHA-256 and
    # validated by the clean-room extraction verification.
    f"{NS}/claim_graph/",
    f"{NS}/artifact_identity/",
    f"{NS}/schema_versioning/",
    # runtime integrity outputs are regenerated by the verification
    # process AFTER the manifest is finalized; pinning them here would
    # be circular. They are covered by re-running the monitor in the
    # extracted release and by the repo-side records.
    f"{NS}/security/zip_scan_report.json",
    f"{NS}/integrity/integrity_monitor_report.json",
    f"{NS}/integrity/change_ledger.jsonl",
    f"{NS}/drift/drift_report.json",
    # the integrity snapshot pins this manifest (sha) and this lock;
    # listing the snapshot here would create a manifest<->snapshot
    # finalize circle. The snapshot is verified by re-running the
    # monitor (protected-artifact checks) and is listed by the
    # ZIP-time root manifest.
    f"{NS}/integrity/",
    # the update-namespace observability view is a post-manifest
    # runtime status (it reads the final monitor + drift states);
    # covered by the ZIP-time root manifest.
    f"{NS}/observability/",
)


def git(args):
    return subprocess.run(["git", "-C", REPO_ROOT] + args,
                          capture_output=True, text=True, check=False)


def role_for(rel):
    if rel.startswith("data_quality_platform/rules/"):
        return "frozen V1 rule source"
    if rel.startswith(OFFICIAL_EVIDENCE_DIR + "/"):
        return "official 3M run-pair evidence"
    if rel == "scripts/final_3m_validation.py":
        return "official checker"
    if rel == "scripts/verify_run_pair.py":
        return "run-pair verifier"
    if rel.startswith("data_quality_platform/"):
        return "platform source"
    if rel.startswith("tests/"):
        return "test suite"
    if rel.startswith("tools/"):
        return "update tooling"
    if rel.startswith("scripts/"):
        return "verification tooling"
    if rel.startswith("evidence/"):
        return "evidence"
    if rel.endswith(".md"):
        return "documentation"
    return "release file"


def artifact_identity(rel):
    """Logical identity (role-based), NOT raw bytes (§23)."""
    return f"{role_for(rel)}::{rel}"


def main():
    started = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    head = git(["rev-parse", "HEAD"]).stdout.strip()
    tree_hash = git(["rev-parse", "HEAD^{tree}"]).stdout.strip()

    tracked = [p for p in git(["ls-files", "-z"]).stdout.split("\0") if p]

    entries = []
    for rel in sorted(tracked):
        if any(rel.startswith(p) for p in SELF_REFERENTIAL_PREFIXES):
            continue  # the lock/manifest cannot describe themselves
        abs_p = os.path.join(REPO_ROOT, rel)
        if not os.path.isfile(abs_p):
            continue
        entries.append({
            "path": rel,
            "sha256": sha256_file(abs_p),
            "size": os.path.getsize(abs_p),
            "role": role_for(rel),
            "artifact_identity": artifact_identity(rel),
        })

    # duplicate identity check (§23) — fail before writing if any
    seen = {}
    for e in entries:
        key = e["artifact_identity"]
        if key in seen:
            print(f"FATAL: duplicate artifact identity: {key}")
            return 4
        seen[key] = True

    # evidence + dependency fingerprints
    fr_update = json.load(open(os.path.join(
        REPO_ROOT, NS, "final_results",
        "FINAL_RESULTS_PORTABLE_2026-09-18.json"), encoding="utf-8"))
    graph = json.load(open(os.path.join(
        REPO_ROOT, NS, "dependency_graph", "dependency_graph.json"),
        encoding="utf-8"))

    manifest_concat = hashlib.sha256()
    for e in entries:
        manifest_concat.update(
            e["path"].encode() + b"\x00" + e["sha256"].encode())
    manifest_sha = manifest_concat.hexdigest()

    manifest = {
        "report": "DQAEIP portable release cryptographic release manifest",
        "schema": {"name": "dqaeip.release_manifest", "version": "1.0"},
        "release_id": RELEASE_ID,
        "generated_utc": started,
        "git_head": head,
        "git_tree": tree_hash,
        "file_count": len(entries),
        "manifest_sha256_concat": manifest_sha,
        "self_referential_exclusions": list(SELF_REFERENTIAL_PREFIXES),
        "exclusion_note": ("the release lock, the manifest and the ZIP "
                           "scan report are written after the manifest "
                           "and therefore cannot be described by it; "
                           "their identities are pinned in the "
                           "integrity snapshot instead"),
        "files": entries,
    }

    os.makedirs(os.path.dirname(MANIFEST_OUT), exist_ok=True)
    with open(MANIFEST_OUT, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")

    lock = {
        "report": "DQAEIP portable release lock (section 33)",
        "release_id": RELEASE_ID,
        "locked_utc": started,
        "status": "LOCKED",
        "final_results_sha256": sha256_file(os.path.join(
            REPO_ROOT, NS, "final_results",
            "FINAL_RESULTS_PORTABLE_2026-09-18.json")),
        "root_final_results_sha256": sha256_file(os.path.join(
            REPO_ROOT, "FINAL_RESULTS.json")),
        "evidence_fingerprint": fr_update.get("dependency_fingerprint"),
        "dependency_fingerprint": graph.get("graph_fingerprint"),
        "frozen_v1_sha256": sha256_file(os.path.join(
            REPO_ROOT, FROZEN_V1_SOURCE)),
        "official_input_sha256": OFFICIAL_INPUT_SHA256,
        "official_output_sha256": OFFICIAL_OUTPUT_SHA256,
        "release_manifest_sha256": sha256_file(MANIFEST_OUT),
        "release_manifest_concat_sha256": manifest_sha,
        "invalidated": False,
        "invalidation_note": ("any subsequent modification to a locked "
                              "artifact INVALIDATES this lock; a locked "
                              "release MUST NOT silently change"),
    }
    with open(LOCK_OUT, "w", encoding="utf-8") as f:
        json.dump(lock, f, indent=2, sort_keys=True)
        f.write("\n")

    print(f"RELEASE MANIFEST -> {NS}/release_manifest/release_manifest.json")
    print(f"  files: {len(entries)} | concat SHA: {manifest_sha[:16]}...")
    print(f"RELEASE LOCK -> {NS}/release_manifest/release_lock.json")
    print(f"  status: LOCKED | release: {RELEASE_ID}")
    print(f"  FINAL_RESULTS(update) SHA: "
          f"{lock['final_results_sha256'][:16]}...")
    print(f"  dependency fingerprint: "
          f"{lock['dependency_fingerprint'][:16]}...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
