#!/usr/bin/env python3
"""DQAEIP FINAL PORTABLE EVIDENCE UPDATE V2 (2026-09-18) — Phase 1.

COMPLETE JSON PATH INVENTORY (task-book Phase 1). READ-ONLY.

Scans EVERY ``evidence/**/*.json`` and ``evidence/**/*.jsonl`` file
(do NOT assume only the official FINAL 3M JSON is affected) and walks
every nested string value, classifying each PATH-LIKE value into the
task-book taxonomy:

    REPO_LOCAL_ABSOLUTE        repository-root-prefixed machine path
    WINDOWS_ABSOLUTE           drive-letter path (C:\\...)
    UNC_PATH                   \\\\server\\share path
    RELATIVE_PATH              portable repo-relative reference
    REPO_URI                   repo:// logical identity
    URL                        http(s)/ftp/git/... URL (NOT a
                               filesystem path — never normalized)
    EXTERNAL_ENVIRONMENT_PATH  non-repository machine path (subtype
                               reason: interpreter_home /
                               external_archive / temp_capture /
                               system_tree / other_external)
    NON_PATH_STRING            not path-like (aggregated count only)
    UNKNOWN                    ambiguous path-like (recorded,
                               protected — never auto-normalized)

Per-value record: source_file, json_path, original_value,
path_classification, classification_reason, proposed_normalized_value,
action (+ detector / artifact_class where applicable).

File disposition (explicit, fail-safe):

    CREATE_UPDATE_V2_PORTABLE_COPY  for the AUTHORITATIVE official 3M
        evidence files carrying machine paths (policy A) AND for the
        code-verified regenerable release-gate replay fixtures
        (evidence/release_gate/replay_work*/, repro_check/ —
        regenerated by scripts/release_gate.py gate_replay and the
        reproducibility capture; the previous session left them
        UNKNOWN-protected; UPDATE V2 closes this portability gap)
    PRESERVE_HISTORICAL            superseded / dated historical
                                   namespaces (no copy — rewriting
                                   history is forbidden)
    PRESERVE_UNKNOWN_PROTECTED     unknown artifacts (never
                                   auto-normalized)
    ALREADY_PORTABLE               no machine-local path findings

Machine-path detection reuses the ONE shared detector set
(data_quality_platform/assurance/portable_evidence.MACHINE_PATH_DETECTORS)
— no independent regex replacements.
"""

import glob
import hashlib
import json
import os
import re
import sys
import time

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from data_quality_platform.assurance.portable_evidence import (  # noqa: E402
    MACHINE_PATH_DETECTORS)

UPDATE_ID = "DQAEIP-FINAL-UPDATE-V2-2026-09-18"
NS = "evidence/FINAL_CLEAN_REBUILD_RELEASE_2026-09-18"
OUT = os.path.join(REPO_ROOT, NS, "path_forensics",
                   "path_inventory_UPDATE-V2.json")

CLASSIFICATION_MAP = os.path.join(
    REPO_ROOT, "evidence", "FINAL_CLEAN_REBUILD_RELEASE_2026-09-18",
    "baseline", "authoritative_inventory.json")

REPO_ROOT_ABS = REPO_ROOT.rstrip("/") + "/"
DOWNLOAD_ABS = os.path.abspath(os.path.join(
    os.path.dirname(os.path.dirname(REPO_ROOT)), "download")) + "/"

# the ONE non-repository environment prefix the established portability
# policy maps to explicit placeholder tokens inside derived copies
UV_PYTHON_PREFIX = re.compile(r"^/home/[^/]+/\.local/share/uv/python/([^/]+)")

URL_RE = re.compile(
    r"(?<![A-Za-z0-9])((?:https?|ftp|sftp|git|ssh)://[^\s\"'<>]+)")

# repo top-level directories — a multi-segment slash string rooted at
# one of these (or carrying a known file extension) is a RELATIVE_PATH
REPO_TOP_DIRS = {
    "airflow", "configs", "data", "data_quality_platform", "docs",
    "evidence", "reports", "runner", "scripts", "sql", "tests", "tools",
}
FILE_EXT_RE = re.compile(
    r"\.(py|json|jsonl|md|txt|csv|tsv|yaml|yml|toml|sql|cfg|ini|log|"
    r"sh|xml|html|css|js)$", re.IGNORECASE)
RELATIVE_FULL_RE = re.compile(
    r"^(\./|\.\./|[A-Za-z0-9_.-])([A-Za-z0-9_.\- ./]*[A-Za-z0-9_.-])$")


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def machine_hit(value):
    """First shared-detector id firing on the value, else None."""
    for det_id, pattern in MACHINE_PATH_DETECTORS:
        if pattern.search(value):
            return det_id
    return None


def classify_value(value):
    """Classify one string into the 9-way taxonomy.

    Returns (classification, reason, proposed, action, detector) where
    proposed is the proposed normalized value (None = keep as-is).
    """
    if not isinstance(value, str) or not value:
        return ("NON_PATH_STRING", "empty or non-string", None,
                "NOT_PATH", None)

    det = machine_hit(value)
    if det is not None:
        # machine-local path family — sub-classify
        if REPO_ROOT_ABS in value:
            proposed = value.replace(REPO_ROOT_ABS, "")
            if proposed == "":
                proposed = "."
            return ("REPO_LOCAL_ABSOLUTE",
                    "embeds this repository's machine-local root "
                    f"prefix (detector {det}); repo-relative POSIX "
                    "form is the established canonical representation",
                    proposed, "NORMALIZE_REPO_LOCAL_IN_DERIVED_COPY", det)
        m = UV_PYTHON_PREFIX.match(value)
        if m:
            token = f"<<uv-python:{m.group(1)}>>"
            proposed = re.sub(
                r"^/home/[^/]+/\.local/share/uv/python/([^/]+)/",
                token + "/", value)
            return ("EXTERNAL_ENVIRONMENT_PATH",
                    "uv-managed cpython interpreter home on the "
                    "authoring machine (detector "
                    f"{det}); established policy maps it to the "
                    "explicit placeholder token in derived copies",
                    proposed, "PLACEHOLDER_IN_DERIVED_COPY", det)
        if value.startswith(DOWNLOAD_ABS) or DOWNLOAD_ABS in value:
            return ("EXTERNAL_ENVIRONMENT_PATH",
                    "machine-local path outside the repository "
                    "(release-archives download directory); external "
                    "system/tool reference — portability policy "
                    "forbids converting it into a repository path",
                    None, "RETAIN_EXTERNAL_DOCUMENTED", det)
        if det in ("windows_drive", "unc_share"):
            cls = "WINDOWS_ABSOLUTE" if det == "windows_drive" else "UNC_PATH"
            return (cls,
                    "Windows %s path (detector %s); no repository "
                    "mapping exists — preserved" % (
                        "drive-letter" if det == "windows_drive"
                        else "UNC share", det),
                    None, "RETAIN_EXTERNAL_DOCUMENTED", det)
        if "/tmp/" in value or "/var/tmp/" in value:
            return ("EXTERNAL_ENVIRONMENT_PATH",
                    "machine-local temporary-directory capture "
                    f"(detector {det}); external environment reference",
                    None, "RETAIN_EXTERNAL_DOCUMENTED", det)
        return ("EXTERNAL_ENVIRONMENT_PATH",
                "machine-local path outside the repository "
                f"(detector {det}); external environment/system "
                "reference — never silently converted to a repo path",
                None, "RETAIN_EXTERNAL_DOCUMENTED", det)

    # URL (checked before relative: a URL never starts with / or a
    # drive letter, so order vs machine-detectors is safe either way)
    if URL_RE.search(value):
        return ("URL",
                "URL (web scheme) — NOT a filesystem path; must remain "
                "a URL, never normalized",
                None, "RETAIN_URL", None)

    if value.startswith("repo://"):
        return ("REPO_URI",
                "repo:// logical artifact identity URI (portable by "
                "construction)",
                None, "RETAIN_PORTABLE", None)

    # relative path — full-string match, no machine markers
    if ("/" in value and RELATIVE_FULL_RE.match(value)
            and not value.startswith("//")):
        segs = [s for s in value.split("/") if s not in (".", "..")]
        first = value.split("/")[0]
        if segs and (first in REPO_TOP_DIRS
                     or FILE_EXT_RE.search(segs[-1])):
            return ("RELATIVE_PATH",
                    "portable repo-relative POSIX reference "
                    "(%s)" % (
                        "rooted at a repository top-level directory"
                        if first in REPO_TOP_DIRS
                        else "file-extension-bearing path"),
                    None, "RETAIN_PORTABLE", None)
        return ("UNKNOWN",
                "slash-bearing string that is path-like but cannot be "
                "safely attributed (no known repository root, no file "
                "extension); fail-safe: recorded and protected, never "
                "auto-normalized",
                None, "PRESERVE_UNKNOWN_PROTECTED", None)

    return ("NON_PATH_STRING",
            "no path-like structure detected", None, "NOT_PATH", None)


def artifact_class_of(rel, cmap):
    entry = cmap.get(rel)
    map_class = entry.get("classification") if isinstance(entry, dict) \
        else None
    if map_class:
        return map_class, "authoritative_inventory classification map"
    if rel.startswith("evidence/FINAL_CLEAN_REBUILD_RELEASE_2026-09-18/"):
        return "DERIVED", "portable-release namespace (derived by " \
                          "construction)"
    if rel.startswith(NS + "/"):
        return "DERIVED", "UPDATE-V2 namespace (derived by construction)"
    return "UNKNOWN", "not present in the classification map"


def file_disposition(rel, machine_findings, art_class, map_source):
    """File-level action (fail-safe, explicit)."""
    has_repo_local = any(
        f["path_classification"] == "REPO_LOCAL_ABSOLUTE"
        for f in machine_findings)
    has_env = any(
        f["path_classification"] == "EXTERNAL_ENVIRONMENT_PATH"
        for f in machine_findings)
    has_windows = any(
        f["path_classification"] in ("WINDOWS_ABSOLUTE", "UNC_PATH")
        for f in machine_findings)

    if not (has_repo_local or has_env or has_windows):
        return ("ALREADY_PORTABLE",
                "no machine-local path values in this file")

    if rel.startswith("evidence/validation/2026-09-18/fresh_3m2/harness/"):
        return ("CREATE_UPDATE_V2_PORTABLE_COPY",
                "AUTHORITATIVE official 3M run evidence (protected "
                "namespace, policy A): original preserved byte-exact; "
                "a clearly-marked UPDATE-V2 portable derived copy is "
                "created")
    if (rel.startswith("evidence/release_gate/replay_work/")
            or rel.startswith("evidence/release_gate/replay_work_neg/")
            or rel.startswith("evidence/release_gate/repro_check/")):
        return ("CREATE_UPDATE_V2_PORTABLE_COPY",
                "regenerable release-gate replay fixture "
                "(regenerated by scripts/release_gate.py gate_replay "
                "on every gate run / reproducibility capture); "
                "classification UNKNOWN in the previous inventory is "
                "resolved to DERIVED-regenerable by code reference — "
                "UPDATE V2 closes this portability gap; original "
                "preserved byte-exact, portable derived copy created")
    if art_class == "AUTHORITATIVE":
        return ("CREATE_UPDATE_V2_PORTABLE_COPY",
                "AUTHORITATIVE artifact with machine paths (policy A)")
    if art_class == "DERIVED":
        return ("PRESERVE_UNKNOWN_PROTECTED",
                "derived artifact with machine paths but no verified "
                "regenerator mapping — fail-safe: no automatic copy; "
                "flagged for review")
    if art_class == "SUPERSEDED":
        return ("PRESERVE_HISTORICAL",
                "superseded historical evidence; preserved as record "
                "(rewriting history is forbidden)")
    return ("PRESERVE_UNKNOWN_PROTECTED",
            "UNKNOWN artifacts are protected; never auto-normalized "
            f"(class source: {map_source})")


def walk_strings(obj, path, container, records):
    if isinstance(obj, dict):
        for k in obj.keys():
            walk_strings(obj[k], f"{path}.{k}", container, records)
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            walk_strings(item, f"{path}[{i}]", container, records)
    elif isinstance(obj, str):
        records.append((path, obj))


def scan_file(fp_rel):
    findings = []
    n_strings = 0
    with open(os.path.join(REPO_ROOT, fp_rel), encoding="utf-8") as f:
        if fp_rel.endswith(".jsonl"):
            for li, line in enumerate(f, start=1):
                line = line.strip()
                if not line:
                    continue
                try:
                    doc = json.loads(line)
                except json.JSONDecodeError:
                    findings.append({
                        "source_file": fp_rel,
                        "json_path": f"$[line {li}]",
                        "original_value": None,
                        "path_classification": "UNKNOWN",
                        "classification_reason": "unparseable JSONL line",
                        "proposed_normalized_value": None,
                        "action": "PRESERVE_UNKNOWN_PROTECTED",
                    })
                    continue
                recs = []
                walk_strings(doc, f"$[line {li}]", "jsonl", recs)
                for p, v in recs:
                    n_strings += 1
                    cls, reason, prop, action, det = classify_value(v)
                    if cls != "NON_PATH_STRING":
                        findings.append({
                            "source_file": fp_rel,
                            "json_path": p,
                            "original_value": v,
                            "path_classification": cls,
                            "classification_reason": reason,
                            "proposed_normalized_value": prop,
                            "action": action,
                            **({"detector": det} if det else {}),
                        })
        else:
            doc = json.load(f)
            recs = []
            walk_strings(doc, "$", "json", recs)
            for p, v in recs:
                n_strings += 1
                cls, reason, prop, action, det = classify_value(v)
                if cls != "NON_PATH_STRING":
                    findings.append({
                        "source_file": fp_rel,
                        "json_path": p,
                        "original_value": v,
                        "path_classification": cls,
                        "classification_reason": reason,
                        "proposed_normalized_value": prop,
                        "action": action,
                        **({"detector": det} if det else {}),
                    })
    return findings, n_strings


def main():
    started = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    with open(CLASSIFICATION_MAP, encoding="utf-8") as f:
        cmap = json.load(f)["full_classification"]

    json_files = sorted(glob.glob(
        os.path.join(REPO_ROOT, "evidence", "**", "*.json"),
        recursive=True))
    jsonl_files = sorted(glob.glob(
        os.path.join(REPO_ROOT, "evidence", "**", "*.jsonl"),
        recursive=True))

    all_findings = []
    file_records = {}
    total_strings = 0
    parse_errors = []

    for fp in json_files + jsonl_files:
        rel = os.path.relpath(fp, REPO_ROOT).replace(os.sep, "/")
        # the inventory's own output namespace is excluded from the
        # scan (it necessarily QUOTES the originals; it did not exist
        # at baseline time)
        if rel.startswith(NS + "/"):
            continue
        try:
            findings, n = scan_file(rel)
        except (OSError, json.JSONDecodeError) as exc:
            parse_errors.append({"file": rel, "error": str(exc)})
            continue
        total_strings += n
        all_findings.extend(findings)
        art_class, map_source = artifact_class_of(rel, cmap)
        machine_findings = [
            x for x in findings if x["path_classification"] in (
                "REPO_LOCAL_ABSOLUTE", "WINDOWS_ABSOLUTE", "UNC_PATH",
                "EXTERNAL_ENVIRONMENT_PATH")]
        disposition, disp_reason = file_disposition(
            rel, machine_findings, art_class, map_source)
        cls_counts = {}
        for x in findings:
            cls_counts[x["path_classification"]] = \
                cls_counts.get(x["path_classification"], 0) + 1
        file_records[rel] = {
            "path_classification_counts": cls_counts,
            "machine_path_findings": len(machine_findings),
            "artifact_class": art_class,
            "artifact_class_source": map_source,
            "disposition": disposition,
            "disposition_reason": disp_reason,
            "sha256": sha256_file(fp),
        }

    by_class = {}
    for x in all_findings:
        by_class[x["path_classification"]] = \
            by_class.get(x["path_classification"], 0) + 1
    by_action = {}
    for x in all_findings:
        by_action[x["action"]] = by_action.get(x["action"], 0) + 1
    by_disposition = {}
    for r in file_records.values():
        by_disposition[r["disposition"]] = \
            by_disposition.get(r["disposition"], 0) + 1

    copy_files = sorted(
        rel for rel, r in file_records.items()
        if r["disposition"] == "CREATE_UPDATE_V2_PORTABLE_COPY")

    doc = {
        "report": "DQAEIP FINAL PORTABLE EVIDENCE UPDATE V2 — Phase 1 "
                  "complete JSON path inventory",
        "schema": {"name": "dqaeip.update_v2.path_inventory",
                   "version": "1.0"},
        "update_id": UPDATE_ID,
        "generated_utc": started,
        "scope": {
            "globs": ["evidence/**/*.json", "evidence/**/*.jsonl"],
            "scanned_files": len(file_records),
            "json_files": len([f for f in json_files
                               if not f.startswith(
                                   os.path.join(REPO_ROOT, NS))]),
            "jsonl_files": len(jsonl_files),
            "excluded": [NS + "/ (this inventory's own namespace — did "
                             "not exist at baseline)"],
            "parse_errors": parse_errors,
            "string_values_scanned": total_strings,
            "classification_note": "URLs are NOT filesystem paths and "
                                  "are never normalized; "
                                  "NON_PATH_STRING values are counted "
                                  "in aggregate only",
        },
        "taxonomy": [
            "REPO_LOCAL_ABSOLUTE", "WINDOWS_ABSOLUTE", "UNC_PATH",
            "RELATIVE_PATH", "REPO_URI", "URL",
            "EXTERNAL_ENVIRONMENT_PATH", "NON_PATH_STRING", "UNKNOWN",
        ],
        "summary": {
            "files_scanned": len(file_records),
            "files_with_path_like_findings": len(
                [1 for r in file_records.values()
                 if sum(r["path_classification_counts"].values()) > 0]),
            "findings_total": len(all_findings),
            "by_classification": by_class,
            "by_action": by_action,
            "by_file_disposition": by_disposition,
            "non_path_strings_aggregate": total_strings
            - len(all_findings),
            "files_selected_for_update_v2_portable_copy":
                len(copy_files),
        },
        "selected_for_portable_copy": copy_files,
        "files": file_records,
        "findings": all_findings,
    }

    os.makedirs(os.path.dirname(os.path.join(REPO_ROOT, OUT)),
                exist_ok=True)
    with open(os.path.join(REPO_ROOT, OUT), "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, sort_keys=True)
        f.write("\n")

    print(f"UPDATE-V2 path inventory written: {OUT}")
    print(f"  files scanned:        {len(file_records)}")
    print(f"  string values:        {total_strings}")
    print(f"  path-like findings:   {len(all_findings)}")
    print(f"  by classification:    {json.dumps(by_class, sort_keys=True)}")
    print(f"  by disposition:       {json.dumps(by_disposition, sort_keys=True)}")
    print(f"  files for V2 copy:    {len(copy_files)}")
    for c in copy_files:
        print(f"    - {c}")
    if parse_errors:
        print(f"  PARSE ERRORS: {parse_errors}")
        return 4
    return 0


if __name__ == "__main__":
    sys.exit(main())
